In [ ]:
a=[[2,3],[4,6]]

In [2]:
import numpy as np

In [ ]:
b=np.asarray(a,order='F')

In [ ]:
print(b)

[[2 3]
 [4 6]]


In [ ]:
for i in np.nditer(b):
  print(i)

2
4
3
6


In [ ]:
a=np.zeros([2,3])

In [ ]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b=np.full([2,3,3],10)

In [ ]:
print(b)

[[[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]]


In [ ]:
c=np.ones([2,3])

In [ ]:
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
x=np.random.rand(2,4,4)

In [ ]:
print(x)

[[[0.582861   0.69231696 0.05430663 0.13717956]
  [0.77504041 0.70275346 0.07372685 0.17674932]
  [0.00159895 0.07058582 0.89175702 0.50841182]
  [0.99650423 0.60992598 0.79045007 0.67675396]]

 [[0.88553439 0.87390659 0.46737003 0.39537177]
  [0.42563301 0.38085241 0.32288778 0.01330665]
  [0.39987262 0.06279163 0.49877754 0.82917541]
  [0.02563508 0.33776993 0.46717198 0.38441873]]]


In [ ]:
c=np.eye(4)

In [ ]:
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
y=np.arange(10,20,3)

In [ ]:
print(y)

[10 13 16 19]


In [ ]:
a=np.arange(1,11,1)

In [ ]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
c=np.linspace(10,20,10,endpoint=False,retstep=True,dtype=int)

In [ ]:
print(c)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), 1.0)


In [ ]:
d=np.logspace(1,20,10,base=2)

In [ ]:
print(d)

[2.00000000e+00 8.64047791e+00 3.73289293e+01 1.61269894e+02
 6.96724480e+02 3.01001624e+03 1.30039894e+04 5.61803417e+04
 2.42712501e+05 1.04857600e+06]


In [ ]:
a=np.arange(1,10,1)

In [ ]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a=a.reshape(3,3)

In [ ]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.size(a)

9

In [ ]:
np.shape(a)

(3, 3)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a=np.array([[2,4],[6,10]])

In [ ]:
a[0][1]

4

In [ ]:
s=np.arange(1,10,1)

In [ ]:
s[2:5]

array([3, 4, 5])

In [ ]:
b=np.copy(s)

In [ ]:
print(b)

[1 2 3 4 5 6 7 8 9]


In [ ]:
c=np.array([[2,3,4],[5,7,8]])

In [ ]:
print(c)

[[2 3 4]
 [5 7 8]]


In [ ]:
b=np.copy(c)

In [ ]:
c,b

(array([[2, 3, 4],
        [5, 7, 8]]), array([[2, 3, 4],
        [5, 7, 8]]))

In [ ]:
d=b.view()

In [ ]:
print(d)

[[2 3 4]
 [5 7 8]]


In [ ]:
print("a=",c)
print("b=",b)
print("c=",d)

a= [[2 3 4]
 [5 7 8]]
b= [[2 3 4]
 [5 7 8]]
c= [[2 3 4]
 [5 7 8]]


In [ ]:
c[0][1]=200

In [ ]:
print(c)

[[  2 200   4]
 [  5   7   8]]


In [ ]:
print(b)

[[2 3 4]
 [5 7 8]]


In [ ]:
b[0][2]=1000

In [ ]:
print(d)

[[   2    3 1000]
 [   5    7    8]]


In [ ]:
np.sort(b, axis=0)

array([[   2,    3,    8],
       [   5,    7, 1000]])

In [ ]:
np.sort(b, axis=1)

array([[   2,    3, 1000],
       [   5,    7,    8]])

In [ ]:
d=np.dtype([('name','S1'),('perc','int')])


In [ ]:
marks=np.array([('hari',20),('raju',80),('ravi',50)],dtype=d)

In [ ]:
print(marks)

[(b'h', 20) (b'r', 80) (b'r', 50)]


In [ ]:
np.sort(marks,order='name')

array([(b'h', 20), (b'r', 50), (b'r', 80)],
      dtype=[('name', 'S1'), ('perc', '<i8')])

In [ ]:
a=np.array([[2,5],[4,10]])

In [ ]:
b=np.array([[1,3],[6,9]])

In [ ]:
np.append(a,b)

array([ 2,  5,  4, 10,  1,  3,  6,  9])

In [ ]:
np.insert(a,3,20)  #array,index,elements

array([ 2,  5,  4, 20, 10])

In [ ]:
np.delete(a,3)

array([2, 5, 4])

In [ ]:
np.concatenate((a,b),axis=1)

array([[ 2,  5,  1,  3],
       [ 4, 10,  6,  9]])

In [ ]:
a,b

(array([[ 2,  5],
        [ 4, 10]]), array([[1, 3],
        [6, 9]]))

In [ ]:
np.concatenate((a,b),axis=0)

array([[ 2,  5],
       [ 4, 10],
       [ 1,  3],
       [ 6,  9]])

In [ ]:
np.stack((a,b))

array([[[ 2,  5],
        [ 4, 10]],

       [[ 1,  3],
        [ 6,  9]]])

In [ ]:
np.stack((a,b),axis=1)

array([[[ 2,  5],
        [ 1,  3]],

       [[ 4, 10],
        [ 6,  9]]])

In [ ]:
np.vstack((a,b))

array([[ 2,  5],
       [ 4, 10],
       [ 1,  3],
       [ 6,  9]])

In [ ]:
np.hstack((a,b))

array([[ 2,  5,  1,  3],
       [ 4, 10,  6,  9]])

In [ ]:
a

array([[ 2,  5],
       [ 4, 10]])

In [ ]:
b

array([[1, 3],
       [6, 9]])

In [ ]:
np.dstack((a,b))

array([[[ 2,  1],
        [ 5,  3]],

       [[ 4,  6],
        [10,  9]]])

In [ ]:
x=np.arange(10,100,10)

In [ ]:
print(x)

[10 20 30 40 50 60 70 80 90]


In [ ]:
s1,s2,s3=np.split(x,3)

In [ ]:
print(s1)

[10 20 30]


In [ ]:
d=np.arange(10,130,10)

In [ ]:
np.split(d,(2,6))

[array([10, 20]),
 array([30, 40, 50, 60]),
 array([ 70,  80,  90, 100, 110, 120])]

In [ ]:
m=np.arange(10,130,10).reshape(4,3)

In [ ]:
np.where(m==80)

(array([2]), array([1]))

In [ ]:
c=np.arange(10,100,10)

In [ ]:
r=np.where(c==20)

In [ ]:
print(r)

(array([1]),)


In [ ]:
np.where(c%20==0)

(array([1, 3, 5, 7]),)

In [ ]:
q=np.array([10,20,40,30,5])


In [ ]:
print(q)

[10 20 40 30  5]


In [ ]:
np.searchsorted(q,10)

0

In [ ]:
np.searchsorted(q,[20,40,30])

array([1, 5, 2])

In [ ]:
a=np.array([[2,3,4],[10,11,12]])
b=np.array([[5,6,7],[13,14,15]])

In [ ]:
np.add(a,b)

array([[ 7,  9, 11],
       [23, 25, 27]])

In [ ]:
np.subtract(a,b)

array([[-3, -3, -3],
       [-3, -3, -3]])

In [ ]:
np.multiply(a,b)

array([[ 10,  18,  28],
       [130, 154, 180]])

In [ ]:
np.divide(a,b)

array([[0.4       , 0.5       , 0.57142857],
       [0.76923077, 0.78571429, 0.8       ]])

In [ ]:
np.exp(a)

array([[7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [ ]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 2.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [ ]:
c=a=np.array([[2,3,4],[10,11,12]])

In [ ]:
np.array_equal(a,c)

True

In [ ]:
a==b

array([[False, False, False],
       [False, False, False]])

In [ ]:
np.min(a)

2

In [ ]:
np.min(a,axis=1)

array([ 2, 10])

In [ ]:
np.max(a,axis=0)

array([10, 11, 12])

In [ ]:
np.sum(a)

42

In [ ]:
a

array([[ 2,  3,  4],
       [10, 11, 12]])

In [ ]:
np.sum(a,axis=0)

array([12, 14, 16])

In [ ]:
np.sum(a,axis=1)

array([ 9, 33])

In [ ]:
np.median(a,axis=0)

array([6., 7., 8.])

In [ ]:
np.var(a)

16.666666666666668

In [ ]:
np.mean(a)

7.0

In [ ]:
np.var(a,axis=0)

array([16., 16., 16.])

In [3]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])