In [1]:
import numpy as np

In [2]:
a=np.array([1,34,5])

In [3]:
print(a)

[ 1 34  5]


In [4]:
b=np.array(56) # Zero Dimensional Array 

In [5]:
c=np.array([1,2,3]) # array of 0D Elements is 1D Array

In [6]:
d=np.array([[1,2,3],[10,12,15]]) #Array of 1D elements is 2D Array

In [7]:
e=np.array([[[1,2,3],[10,12,15]],[[1,4,3],[10,10,15]]])

In [8]:
#To find the dimensions of Array
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)


1
0
1
2
3


In [9]:
print(type(e))

<class 'numpy.ndarray'>


Creation of Existing Array

In [10]:
# np.asarray(input.dtype,order) "C=row major order,"F"=Column major order

l=[1,2,3]
a=np.asarray(l,float,"C")

In [11]:
print(a)

[1. 2. 3.]


In [12]:
l=[[1,2,3],[6,7,2]]
b=np.asarray(l,dtype=float,order="F")


In [13]:
print(b)

[[1. 2. 3.]
 [6. 7. 2.]]


In [14]:
for i in np.nditer(b):
  print(i)     # by printing the each value u will come to which order it is followingh 

1.0
6.0
2.0
7.0
3.0
2.0


In [15]:
b=np.asarray(l,dtype=float,order="C")


In [16]:
for i in np.nditer(b):
  print(i)

1.0
2.0
3.0
6.0
7.0
2.0


In [17]:
m=b"dillep"
c=np.frombuffer(m, dtype="S1", count=-1,offset=0)

In [18]:
print(c)

[b'd' b'i' b'l' b'l' b'e' b'p']


In [19]:
m=b"dillep"
c=np.frombuffer(m, dtype="S1", count=-1,offset=3)

In [20]:
print(c)

[b'l' b'e' b'p']


In [21]:
m=b"dillep"
c=np.frombuffer(m, dtype="S1", count=5,offset=0)  # given count as 5

In [22]:
print(c)

[b'd' b'i' b'l' b'l' b'e']


In [23]:
m='dileep'

In [24]:
c=np.fromiter(m,dtype='S1')

In [25]:
print(c)

[b'd' b'i' b'l' b'e' b'e' b'p']


In [26]:
m=[1,2,3]

In [27]:
c=np.fromiter(m,dtype='float',count=-1)

In [28]:
print(c)

[1. 2. 3.]


Arange,linespace,logspace

In [29]:
np.arange(1,10,2,int)

array([1, 3, 5, 7, 9])

In [30]:
np.arange(1,10,2,float)

array([1., 3., 5., 7., 9.])

In [31]:
np.linspace(1,20,20,True,True)  #linspace(start,stop,num,endpoint,retstep,dtype)  => 'num is the number of values betweeen intervals default=50

                       # 'endpoint=>true or false which is whether to include stopindex or not. default=True
 
                       # 'retstep' => difference between the elements (True/False) default value False

                       #'dtype'=> float/int 

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20.]), 1.0)

In [32]:
np.linspace(1,20,20,endpoint=False,retstep=True)

(array([ 1.  ,  1.95,  2.9 ,  3.85,  4.8 ,  5.75,  6.7 ,  7.65,  8.6 ,
         9.55, 10.5 , 11.45, 12.4 , 13.35, 14.3 , 15.25, 16.2 , 17.15,
        18.1 , 19.05]), 0.95)

In [33]:
np.logspace(1,20,20,base=2,endpoint=True) ##logspace(start,stop,num,endpoint,base,dtype)

array([2.000000e+00, 4.000000e+00, 8.000000e+00, 1.600000e+01,
       3.200000e+01, 6.400000e+01, 1.280000e+02, 2.560000e+02,
       5.120000e+02, 1.024000e+03, 2.048000e+03, 4.096000e+03,
       8.192000e+03, 1.638400e+04, 3.276800e+04, 6.553600e+04,
       1.310720e+05, 2.621440e+05, 5.242880e+05, 1.048576e+06])

zeros,full,ones,eye

In [34]:
np.shape(a)

(3,)

In [35]:
b.shape

(2, 3)

In [36]:
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
np.full((5,5),50) #full(shape, num)=> num is the elemntwe want in array

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]])

In [39]:
np.eye(6)  #np.eye(rows/colums) rows=colums

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [40]:
a=[1,1,2,3,4,5,6,8,9]

In [41]:
np.reshape(a,(3,3))

array([[1, 1, 2],
       [3, 4, 5],
       [6, 8, 9]])

In [42]:
np.reshape(a,(9,1))

array([[1],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [8],
       [9]])

Accessing & Slicing

In [43]:
e=np.array([[[1,2,3],[10,12,15]],[[1,4,3],[10,10,15]]])
d=np.array([[1,2,3],[10,12,15]])
c=np.array([1,2,3])

In [44]:
print(e[0][0][2])

3


In [45]:
print(e[0][1][-1])

15


In [46]:
print(e[0,1,-1])

15


In [47]:
print(e[0,0,2])

3


In [48]:
print(d[0,2])

3


In [49]:
print(e[-1,-1,-1])

15


In [50]:
a[::]

[1, 1, 2, 3, 4, 5, 6, 8, 9]

In [51]:
a

[1, 1, 2, 3, 4, 5, 6, 8, 9]

In [52]:
a[:5:2]

[1, 2, 4]

In [53]:
d=np.array([[1,2,3],[10,12,15]])

In [54]:
d[1,1]

12

In [55]:
d[0:2,0:2]

array([[ 1,  2],
       [10, 12]])

In [56]:
e=np.array([[[1,2,3],[10,12,15]],[[1,4,3],[10,10,15]]])

In [57]:
e[1,1,:2]

array([10, 10])

In [58]:
e[:2,:2,:2]

array([[[ 1,  2],
        [10, 12]],

       [[ 1,  4],
        [10, 10]]])

In [59]:
d=[[10,2,12],[5,30,20]]

In [60]:
np.sort(d,axis=1)

array([[ 2, 10, 12],
       [ 5, 20, 30]])

In [61]:
np.sort(d,axis=0)

array([[ 5,  2, 12],
       [10, 30, 20]])

In [62]:
e

array([[[ 1,  2,  3],
        [10, 12, 15]],

       [[ 1,  4,  3],
        [10, 10, 15]]])

In [63]:
np.sort(e,axis=1)

array([[[ 1,  2,  3],
        [10, 12, 15]],

       [[ 1,  4,  3],
        [10, 10, 15]]])

In [64]:
x=np.sort(e,axis=0)

In [65]:
print(x)

[[[ 1  2  3]
  [10 10 15]]

 [[ 1  4  3]
  [10 12 15]]]


In [66]:
print(x.dtype)

int64


In [67]:
print(x.astype("f")) #converted to float data type

[[[ 1.  2.  3.]
  [10. 10. 15.]]

 [[ 1.  4.  3.]
  [10. 12. 15.]]]


Copy and View

In [68]:
#copy creates an external array if element changed in array then the elements doesnt get changed
# in the copy array where as in view the changes will get reflected

x

array([[[ 1,  2,  3],
        [10, 10, 15]],

       [[ 1,  4,  3],
        [10, 12, 15]]])

In [69]:
b=x.copy()

In [70]:
c=x.view()

In [71]:
x[0][0][0]=100

In [72]:
print(x)

[[[100   2   3]
  [ 10  10  15]]

 [[  1   4   3]
  [ 10  12  15]]]


In [73]:
print(b)

[[[ 1  2  3]
  [10 10 15]]

 [[ 1  4  3]
  [10 12 15]]]


In [74]:
print(c)

[[[100   2   3]
  [ 10  10  15]]

 [[  1   4   3]
  [ 10  12  15]]]


In [75]:
a=np.array([1,2,3,10,8,20],dtype='f')

In [76]:
a

array([ 1.,  2.,  3., 10.,  8., 20.], dtype=float32)

In [77]:
l=a.copy()

In [78]:
m=a.view()

In [79]:
a[0]=2000.0

In [80]:
l

array([ 1.,  2.,  3., 10.,  8., 20.], dtype=float32)

In [81]:
m

array([2000.,    2.,    3.,   10.,    8.,   20.], dtype=float32)

In [82]:
b=a.astype("U")

In [83]:
b.dtype

dtype('<U32')

In [84]:
c=a.astype(bool)

In [85]:
print(c)

[ True  True  True  True  True  True]


In [86]:
c.dtype

dtype('bool')

In [87]:
a=np.array([[3,4,5],[10,20,5]])
b=np.array([[11,0,6],[100,20,50]])

In [88]:
a

array([[ 3,  4,  5],
       [10, 20,  5]])

In [89]:
b

array([[ 11,   0,   6],
       [100,  20,  50]])

In [90]:
np.concatenate((a,b)) #parameters should be placed in tuple

array([[  3,   4,   5],
       [ 10,  20,   5],
       [ 11,   0,   6],
       [100,  20,  50]])

In [91]:
np.concatenate((a,b),axis=1)

array([[  3,   4,   5,  11,   0,   6],
       [ 10,  20,   5, 100,  20,  50]])

In [92]:
np.stack((a,b))  # stack will form an array with each array as element

array([[[  3,   4,   5],
        [ 10,  20,   5]],

       [[ 11,   0,   6],
        [100,  20,  50]]])

In [93]:
np.stack((a,b) ,axis=1)

array([[[  3,   4,   5],
        [ 11,   0,   6]],

       [[ 10,  20,   5],
        [100,  20,  50]]])

In [94]:
np.stack((a,b),axis=0)

array([[[  3,   4,   5],
        [ 10,  20,   5]],

       [[ 11,   0,   6],
        [100,  20,  50]]])

In [95]:
np.hstack((a,b)) #it is like row conactente (axis=1)

array([[  3,   4,   5,  11,   0,   6],
       [ 10,  20,   5, 100,  20,  50]])

In [96]:
np.vstack((a,b)) #like column concatenate axis=0

array([[  3,   4,   5],
       [ 10,  20,   5],
       [ 11,   0,   6],
       [100,  20,  50]])

In [97]:
np.dstack((a,b)) #take each element from each array and make a rows a forming new array

array([[[  3,  11],
        [  4,   0],
        [  5,   6]],

       [[ 10, 100],
        [ 20,  20],
        [  5,  50]]])

In [98]:
a=np.arange(1,10)

In [99]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [100]:
a*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [101]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [102]:
np.split(a,3) #it will split into equal divisions if not possible will show error

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [103]:
np.array_split(a,2) #it will arrange into arrays though it doesnt have equal  divsions it will divide

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]

In [104]:
d=np.array([[1,2,3],[10,12,15]])

In [105]:
print(d)

[[ 1  2  3]
 [10 12 15]]


In [106]:
print(np.vsplit(d,2)) #vsplit doesnt work on single dimensions

[array([[1, 2, 3]]), array([[10, 12, 15]])]


In [107]:
print(np.hsplit(d,3)) # cannot work with equal division

[array([[ 1],
       [10]]), array([[ 2],
       [12]]), array([[ 3],
       [15]])]


In [109]:
print(np.vsplit(d,2))

[array([[1, 2, 3]]), array([[10, 12, 15]])]


20-03-2022

In [112]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
#where return the index of the given value
 
np.where(a%2==0)  

(array([1, 3, 5, 7]),)

In [114]:
#Searched Sort =>returns the index where the specified value should be inserted.

#Elements should be in sorted order before implementing searchsorted
a=[1,10,3,5,8,7]
a=np.asarray(a)
a=np.sort(a)

In [115]:
print(a)

[ 1  3  5  7  8 10]


In [116]:
np.searchsorted(a,2)

1

In [117]:
np.searchsorted(a,[2,4,6,9,11]) 

array([1, 2, 3, 5, 6])

In [119]:
#sort(array,axis,order,kind) kind as merge sort and quick sort
m=np.array([[30,20,40],[10,300,25]])

In [120]:
np.sort(m,axis=0)

array([[ 10,  20,  25],
       [ 30, 300,  40]])

In [122]:
np.sort(m,axis=1)

array([[ 20,  30,  40],
       [ 10,  25, 300]])

In [123]:
d=np.dtype([('name',"S1"),("Percent", float)])

x=np.array([('abc',60.5),("Arun",90.25),('Abhi',87.5)], dtype=d)

np.sort(x,order="Percent")

array([(b'a', 60.5 ), (b'A', 87.5 ), (b'A', 90.25)],
      dtype=[('name', 'S1'), ('Percent', '<f8')])

In [124]:
np.sort(x,order='name')

array([(b'A', 87.5 ), (b'A', 90.25), (b'a', 60.5 )],
      dtype=[('name', 'S1'), ('Percent', '<f8')])

In [125]:
a=np.array([[2,3,3],[4,5,10],[2,2,2]])
b=np.array([[1,4,5],[0,7,18],[1,5,5]])

In [127]:
np.add(a,b)

array([[ 3,  7,  8],
       [ 4, 12, 28],
       [ 3,  7,  7]])

In [128]:
np.subtract(a,b)

array([[ 1, -1, -2],
       [ 4, -2, -8],
       [ 1, -3, -3]])

In [129]:
np.multiply(a,b)

array([[  2,  12,  15],
       [  0,  35, 180],
       [  2,  10,  10]])

In [130]:
np.divide(a,b)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[2.        , 0.75      , 0.6       ],
       [       inf, 0.71428571, 0.55555556],
       [2.        , 0.4       , 0.4       ]])

In [131]:
c=np.array([10,10,20])

In [132]:
np.add(a,c)

array([[12, 13, 23],
       [14, 15, 30],
       [12, 12, 22]])

In [133]:
d=np.array([10,50])

In [136]:
a

array([[ 2,  3,  3],
       [ 4,  5, 10],
       [ 2,  2,  2]])

In [137]:
c

array([10, 10, 20])

In [139]:
np.divide(a,c)

array([[0.2 , 0.3 , 0.15],
       [0.4 , 0.5 , 0.5 ],
       [0.2 , 0.2 , 0.1 ]])

In [135]:
np.multiply(a,c)

array([[ 20,  30,  60],
       [ 40,  50, 200],
       [ 20,  20,  40]])

In [140]:
np.reciprocal(a) #it will return only integers

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [141]:
np.mod(a,2)

array([[0, 1, 1],
       [0, 1, 0],
       [0, 0, 0]])

In [142]:
np.power(a,b)

array([[                  2,                  81,                 243],
       [                  1,               78125, 1000000000000000000],
       [                  2,                  32,                  32]])

In [143]:
np.power(a,2)

array([[  4,   9,   9],
       [ 16,  25, 100],
       [  4,   4,   4]])

In [144]:
c=[5.0+6.j,2.+1.j,10.+2.j]

In [146]:
np.real(c)

array([ 5.,  2., 10.])

In [147]:
np.imag(c)

array([6., 1., 2.])

In [148]:
np.conjugate(c)

array([ 5.-6.j,  2.-1.j, 10.-2.j])

In [149]:
a

array([[ 2,  3,  3],
       [ 4,  5, 10],
       [ 2,  2,  2]])

In [151]:
np.amin(a)

2

In [152]:
np.amin(a,axis=0)

array([2, 2, 2])

In [153]:
np.amax(a,axis=1)

array([ 3, 10,  2])

In [154]:
np.average(a)

3.6666666666666665

In [155]:
np.mean(a)

3.6666666666666665

In [156]:
w1=[1,2,3]

In [158]:
np.average(a,weights=w1,axis=0)

array([2.66666667, 3.16666667, 4.83333333])

In [159]:
np.mean(a,axis=0)

array([2.66666667, 3.33333333, 5.        ])

In [160]:
a

array([[ 2,  3,  3],
       [ 4,  5, 10],
       [ 2,  2,  2]])

In [161]:
np.median(a)

3.0

In [162]:
np.median(a,axis=0)

array([2., 3., 3.])

In [163]:
np.median(a,axis=1)

array([3., 5., 2.])

In [164]:
np.var(a)

6.000000000000002

In [165]:
np.std(a)

2.4494897427831783

In [167]:
a

array([[ 2,  3,  3],
       [ 4,  5, 10],
       [ 2,  2,  2]])

In [169]:
np.sort(a,kind= "mergesort")

array([[ 2,  3,  3],
       [ 4,  5, 10],
       [ 2,  2,  2]])

In [170]:
np.sort(a)

array([[ 2,  3,  3],
       [ 4,  5, 10],
       [ 2,  2,  2]])