In [13]:
import numpy as np

In [14]:
a=np.array([1,34,5])

In [15]:
print(a)

[ 1 34  5]


In [21]:
b=np.array(56) # Zero Dimensional Array 

In [22]:
c=np.array([1,2,3]) # array of 0D Elements is 1D Array

In [23]:
d=np.array([[1,2,3],[10,12,15]]) #Array of 1D elements is 2D Array

In [24]:
e=np.array([[[1,2,3],[10,12,15]],[[1,4,3],[10,10,15]]])

In [30]:
#To find the dimensions of Array
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)


1
0
1
2
3


In [32]:
print(type(e))

<class 'numpy.ndarray'>


Creation of Existing Array

In [36]:
# np.asarray(input.dtype,order) "C=row major order,"F"=Column major order

l=[1,2,3]
a=np.asarray(l,float,"C")

In [37]:
print(a)

[1. 2. 3.]


In [44]:
l=[[1,2,3],[6,7,2]]
b=np.asarray(l,dtype=float,order="F")


In [45]:
print(b)

[[1. 2. 3.]
 [6. 7. 2.]]


In [50]:
for i in np.nditer(b):
  print(i)     # by printing the each value u will come to which order it is followingh 

1.0
6.0
2.0
7.0
3.0
2.0


In [51]:
b=np.asarray(l,dtype=float,order="C")


In [52]:
for i in np.nditer(b):
  print(i)

1.0
2.0
3.0
6.0
7.0
2.0


In [55]:
m=b"dillep"
c=np.frombuffer(m, dtype="S1", count=-1,offset=0)

In [56]:
print(c)

[b'd' b'i' b'l' b'l' b'e' b'p']


In [57]:
m=b"dillep"
c=np.frombuffer(m, dtype="S1", count=-1,offset=3)

In [58]:
print(c)

[b'l' b'e' b'p']


In [59]:
m=b"dillep"
c=np.frombuffer(m, dtype="S1", count=5,offset=0)  # given count as 5

In [61]:
print(c)

[b'd' b'i' b'l' b'l' b'e']


In [66]:
m='dileep'

In [67]:
c=np.fromiter(m,dtype='S1')

In [69]:
print(c)

[b'd' b'i' b'l' b'e' b'e' b'p']


In [72]:
m=[1,2,3]

In [73]:
c=np.fromiter(m,dtype='float',count=-1)

In [74]:
print(c)

[1. 2. 3.]


Arange,linespace,logspace

In [75]:
np.arange(1,10,2,int)

array([1, 3, 5, 7, 9])

In [77]:
np.arange(1,10,2,float)

array([1., 3., 5., 7., 9.])

In [79]:
np.linspace(1,20,20,True,True)  #linspace(start,stop,num,endpoint,retstep,dtype)  => 'num is the number of values betweeen intervals default=50

                       # 'endpoint=>true or false which is whether to include stopindex or not. default=True
 
                       # 'retstep' => difference between the elements (True/False) default value False

                       #'dtype'=> float/int 

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20.]), 1.0)

In [80]:
np.linspace(1,20,20,endpoint=False,retstep=True)

(array([ 1.  ,  1.95,  2.9 ,  3.85,  4.8 ,  5.75,  6.7 ,  7.65,  8.6 ,
         9.55, 10.5 , 11.45, 12.4 , 13.35, 14.3 , 15.25, 16.2 , 17.15,
        18.1 , 19.05]), 0.95)

In [85]:
np.logspace(1,20,20,base=2,endpoint=True) ##logspace(start,stop,num,endpoint,base,dtype)

array([2.000000e+00, 4.000000e+00, 8.000000e+00, 1.600000e+01,
       3.200000e+01, 6.400000e+01, 1.280000e+02, 2.560000e+02,
       5.120000e+02, 1.024000e+03, 2.048000e+03, 4.096000e+03,
       8.192000e+03, 1.638400e+04, 3.276800e+04, 6.553600e+04,
       1.310720e+05, 2.621440e+05, 5.242880e+05, 1.048576e+06])

zeros,full,ones,eye

In [87]:
np.shape(a)

(3,)

In [88]:
b.shape

(2, 3)

In [90]:
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [92]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [95]:
np.full((5,5),50) #full(shape, num)=> num is the elemntwe want in array

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]])

In [99]:
np.eye(6)  #np.eye(rows/colums) rows=colums

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [100]:
a=[1,1,2,3,4,5,6,8,9]

In [101]:
np.reshape(a,(3,3))

array([[1, 1, 2],
       [3, 4, 5],
       [6, 8, 9]])

In [104]:
np.reshape(a,(9,1))

array([[1],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [8],
       [9]])

Accessing & Slicing

In [108]:
e=np.array([[[1,2,3],[10,12,15]],[[1,4,3],[10,10,15]]])
d=np.array([[1,2,3],[10,12,15]])
c=np.array([1,2,3])

In [107]:
print(e[0][0][2])

3


In [109]:
print(e[0][1][-1])

15


In [110]:
print(e[0,1,-1])

15


In [111]:
print(e[0,0,2])

3


In [112]:
print(d[0,2])

3


In [113]:
print(e[-1,-1,-1])

15


In [114]:
a[::]

[1, 1, 2, 3, 4, 5, 6, 8, 9]

In [115]:
a

[1, 1, 2, 3, 4, 5, 6, 8, 9]

In [116]:
a[:5:2]

[1, 2, 4]

In [120]:
d=np.array([[1,2,3],[10,12,15]])

In [123]:
d[1,1]

12

In [122]:
d[0:2,0:2]

array([[ 1,  2],
       [10, 12]])

In [117]:
e=np.array([[[1,2,3],[10,12,15]],[[1,4,3],[10,10,15]]])

array([[[ 1,  2,  3],
        [10, 12, 15]],

       [[ 1,  4,  3],
        [10, 10, 15]]])

In [119]:
e[1,1,:2]

array([10, 10])

In [127]:
e[:2,:2,:2]

array([[[ 1,  2],
        [10, 12]],

       [[ 1,  4],
        [10, 10]]])

In [139]:
d=[[10,2,12],[5,30,20]]

In [140]:
np.sort(d,axis=1)

array([[ 2, 10, 12],
       [ 5, 20, 30]])

In [141]:
np.sort(d,axis=0)

array([[ 5,  2, 12],
       [10, 30, 20]])

In [142]:
e

array([[[ 1,  2,  3],
        [10, 12, 15]],

       [[ 1,  4,  3],
        [10, 10, 15]]])

In [143]:
np.sort(e,axis=1)

array([[[ 1,  2,  3],
        [10, 12, 15]],

       [[ 1,  4,  3],
        [10, 10, 15]]])

In [148]:
x=np.sort(e,axis=0)

In [151]:
print(x)

[[[ 1  2  3]
  [10 10 15]]

 [[ 1  4  3]
  [10 12 15]]]


In [150]:
print(x.dtype)

int64


In [152]:
print(x.astype("f")) #converted to float data type

[[[ 1.  2.  3.]
  [10. 10. 15.]]

 [[ 1.  4.  3.]
  [10. 12. 15.]]]


Copy and View

In [157]:
#copy creates an external array if element changed in array then the elements doesnt get changed
# in the copy array where as in view the changes will get reflected

x

array([[[ 1,  2,  3],
        [10, 10, 15]],

       [[ 1,  4,  3],
        [10, 12, 15]]])

In [158]:
b=x.copy()

In [160]:
c=x.view()

In [161]:
x[0][0][0]=100

In [164]:
print(x)

[[[100   2   3]
  [ 10  10  15]]

 [[  1   4   3]
  [ 10  12  15]]]


In [162]:
print(b)

[[[ 1  2  3]
  [10 10 15]]

 [[ 1  4  3]
  [10 12 15]]]


In [163]:
print(c)

[[[100   2   3]
  [ 10  10  15]]

 [[  1   4   3]
  [ 10  12  15]]]


In [165]:
a=np.array([1,2,3,10,8,20],dtype='f')

In [166]:
a

array([ 1.,  2.,  3., 10.,  8., 20.], dtype=float32)

In [167]:
l=a.copy()

In [168]:
m=a.view()

In [170]:
a[0]=2000.0

In [171]:
l

array([ 1.,  2.,  3., 10.,  8., 20.], dtype=float32)

In [172]:
m

array([2000.,    2.,    3.,   10.,    8.,   20.], dtype=float32)

In [177]:
b=a.astype("U")

In [178]:
b.dtype

dtype('<U32')

In [180]:
c=a.astype(bool)

In [182]:
print(c)

[ True  True  True  True  True  True]


In [181]:
c.dtype

dtype('bool')

In [184]:
a=np.array([[3,4,5],[10,20,5]])
b=np.array([[11,0,6],[100,20,50]])

In [190]:
a

array([[ 3,  4,  5],
       [10, 20,  5]])

In [191]:
b

array([[ 11,   0,   6],
       [100,  20,  50]])

In [193]:
np.concatenate((a,b)) #parameters should be placed in tuple

array([[  3,   4,   5],
       [ 10,  20,   5],
       [ 11,   0,   6],
       [100,  20,  50]])

In [195]:
np.concatenate((a,b),axis=1)

array([[  3,   4,   5,  11,   0,   6],
       [ 10,  20,   5, 100,  20,  50]])

In [202]:
np.stack((a,b))  # stack will form an array with each array as element

array([[[  3,   4,   5],
        [ 10,  20,   5]],

       [[ 11,   0,   6],
        [100,  20,  50]]])

In [204]:
np.stack((a,b) ,axis=1)

array([[[  3,   4,   5],
        [ 11,   0,   6]],

       [[ 10,  20,   5],
        [100,  20,  50]]])

In [205]:
np.stack((a,b),axis=0)

array([[[  3,   4,   5],
        [ 10,  20,   5]],

       [[ 11,   0,   6],
        [100,  20,  50]]])

In [198]:
np.hstack((a,b)) #it is like row conactente (axis=1)

array([[  3,   4,   5,  11,   0,   6],
       [ 10,  20,   5, 100,  20,  50]])

In [199]:
np.vstack((a,b)) #like column concatenate axis=0

array([[  3,   4,   5],
       [ 10,  20,   5],
       [ 11,   0,   6],
       [100,  20,  50]])

In [201]:
np.dstack((a,b)) #take each element from each array and make a rows a forming new array

array([[[  3,  11],
        [  4,   0],
        [  5,   6]],

       [[ 10, 100],
        [ 20,  20],
        [  5,  50]]])

In [208]:
a=np.arange(1,10)

In [209]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [210]:
a*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [211]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [213]:
np.split(a,3) #it will split into equal divisions if not possible will show error

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [215]:
np.array_split(a,2) #it will arrange into arrays though it doesnt have equal  divsions it will divide

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]

In [220]:
d=np.array([[1,2,3],[10,12,15]])

In [221]:
print(d)

[[ 1  2  3]
 [10 12 15]]


In [230]:
print(np.vsplit(d,2)) #vsplit doesnt work on single dimensions

[array([[1, 2, 3]]), array([[10, 12, 15]])]


In [241]:
print(np.hsplit(d,3)) # cannot work with equal division

[array([[ 1],
       [10]]), array([[ 2],
       [12]]), array([[ 3],
       [15]])]


In [225]:
print(np.vsplit(d,3))

ValueError: ignored